apiVersion: v1
kind: Service
metadata:
  name: udacity-capstone-lb
  labels:
    app: udacity-capstone
spec:
  type: LoadBalancer
  selector:
    app: udacity-capstone
  ports:
    - port: 8000
      targetPort: 8000